remove status check of build since build has been removed

diff --git a/ghDeploy b/ghDeploy
--- a/ghDeploy
+++ b/ghDeploy
@@ -2,11 +2,11 @@
 
 #./build
 
-if [ $? -ne 0 ]
-then
-  echo "BUILD FAILED - NOT DEPLOYING"
-  exit 1
-fi
+#if [ $? -ne 0 ]
+#then
+#  echo "BUILD FAILED - NOT DEPLOYING"
+#  exit 1
+#fi
 
 git checkout gh-pages
 
