add skeleton build script and use it in deploy scripts

diff --git a/ghDeploy b/ghDeploy
--- a/ghDeploy
+++ b/ghDeploy
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+./build
+
+if [ $? -ne 0 ]
+then
+  echo "BUILD FAILED - NOT DEPLOYING"
+  exit 1
+fi
+ 
 git checkout gh-pages
 
 git checkout master -- deployFileList
diff --git a/localDeploy b/localDeploy
--- a/localDeploy
+++ b/localDeploy
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+./build
+
+if [ $? -ne 0 ]
+then
+  echo "BUILD FAILED - NOT DEPLOYING"
+  exit 1
+fi
+
 DEST=/var/www/html/TSP
 
 rm $DEST/*
